<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>AstraClient</RootNamespace>
    <AssemblyName>AstraClient</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.31.0</Version>
    <Authors>Astra</Authors>
    <Product>Astra Client</Product>
    <Description>A modern frosted-glass Minecraft client and launcher.</Description>
    <ApplicationIcon>Assets\astra_logo.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="Svg.Skia" Version="3.1.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\astra_logo.ico" />
    <Resource Include="Assets\Loaders\*.png" />
    <Resource Include="Assets\Loaders\*.svg" />
  </ItemGroup>
</Project>
